version: '3'

services:

  mariadb:
    build:                      
      context: ./requirements/mariadb
      dockerfile: Dockerfile     
    container_name: mariadb-container
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - network


  wordpress:
    container_name: wordpress
    #Create a depedency between the 2 container, db will be launched before
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rafael/data/mysql
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rafael/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
